### ISSUE TITLE
get-feeds.rb chokes on some blog content during encode() step

### ISSUE THREAD

**Issue by Cordelya** [krusynth/webring-starter#1] opened 2023-07-11 14:35 UTC
I've forked this repository to [https://github.com/Cordelya/sca-blogs](https://github.com/Cordelya/sca-blogs) (hosted at [https://cordelya.github.io/sca-blogs](https://cordelya.github.io/sca-blogs)), populated list.json with some blogs, and found that line 107 of get-feeds.rb chokes on the content of two of the blogs in my list.json file.

I've put a band-aid in the form of a rescue block that sets `result['content']` to "" so that it will at least build the site and serve up the members list and nav code.

```rb
        begin
          result['content'] = entry.content.encode('iso-8859-1', :invalid => :replace, :undef => :replace, :replace => '').encode('utf-8', :invalid => :replace, :undef => :replace, :replace => '')
        rescue
          result['content'] = ""
        end
```

However, I am only minimally familiar with Ruby, and am at a loss as to how to deal with the root problem.

For reproducibility, the two blogs that are causing the script to choke are:

* [Konstantia Kaloethina](https://kaloethina.com/)
* [Cordeilla Sharpe](https://cordeilla-sharpe.info)

If I remove those two and leave the remaining three, the build pipeline runs fine. I was also able to reproduce the problem in a local environment.

I'm filing this issue here for two reasons:

* In case anyone else runs into this problem, they can try using the temporary rescue block fix.
* In case anyone would like a puzzle to solve, here's one.

I'm not in any kind of rush to get the root problem solved. My repo's pipeline successfully builds the important parts, so I'm content to leave it as is for now.

**Comment by krusynth** [comment] 2023-07-11 15:24
Honestly that rescue is exactly the way to deal with this. I'd have to do some digging here but it looks like the entity conversion is failing for some reason - often that means that the content is from a language set that is unable to be translated or unknown. Since that can sometimes only be fixed by the person running the site, just setting the content to blank is a perfectly acceptable solution.

That being said, I'll try to take a look this coming weekend at this and see if I can determine the cause.

**Closed as completed** 2023-08-19 22:08 UTC

**Comment by krusynth** [comment] 2023-08-19 22:12
I finally got around to digging into this a bit further and patched it.

The issue was that I was looking for `<content>` when `<description>` is also valid.  `feedjira` parses the latter into `.summary` instead of `.content`, so I just had to account for that. Everything should work now (I hope?) !
